openconnect: avoid propagating SIGINT
There is a possible race condition when `openconnect-sso` is stopped via
CTRL-C, as `openconnect` will too get that signal and may exit before
the parent Python process would clean-up its children. This can cause an
unhandled exception in subprocess.py:

    Traceback (most recent call last):
    File "/usr/lib/python3.7/subprocess.py", line 474, in run
        stdout, stderr = process.communicate(input, timeout=timeout)
    File "/usr/lib/python3.7/subprocess.py", line 931, in communicate
        self.wait()
    File "/usr/lib/python3.7/subprocess.py", line 990, in wait
        return self._wait(timeout=timeout)
    File "/usr/lib/python3.7/subprocess.py", line 1624, in _wait
        (pid, sts) = self._try_wait(0)
    File "/usr/lib/python3.7/subprocess.py", line 1582, in _try_wait
        (pid, sts) = os.waitpid(self.pid, wait_flags)
    KeyboardInterrupt

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "/home/pasja/openconnect/venv/bin/openconnect-sso", line 10, in <module>
        sys.exit(main())
    File "/home/pasja/openconnect/venv/lib/python3.7/site-packages/openconnect_sso/cli.py", line 169, in main
        return app.run(args)
    File "/home/pasja/openconnect/venv/lib/python3.7/site-packages/openconnect_sso/app.py", line 75, in run
        auth_response, selected_profile, args.proxy, args.openconnect_args
    File "/home/pasja/openconnect/venv/lib/python3.7/site-packages/openconnect_sso/app.py", line 186, in run_openconnect
        return subprocess.run(command_line).returncode
    File "/usr/lib/python3.7/subprocess.py", line 481, in run
        process.kill()
    File "/usr/lib/python3.7/subprocess.py", line 1756, in kill
        self.send_signal(signal.SIGKILL)
    File "/usr/lib/python3.7/subprocess.py", line 1746, in send_signal
        os.kill(self.pid, sig)
    PermissionError: [Errno 1] Operation not permitted

To resolve this, `openconnect` is started in a new session via
setsid(2), so it is detached from the controlling terminal and it is
executed in a new process group. This requires a change in `sudo`
invocation as well, as it too won't have a controlling terminal.

References: #39